version: '3'
services:
  frontend.dev:
    build:
      context: .
      dockerfile: ./tools/Dockerfile
    image: frontend:dev
    ports:
      - 9000:9000
    volumes:
      # Do not match everything otherwise you get conflicts of node_modules folder of osx and linux
      - ./public:/app/public/
      - ./src:/app/src/
  frontend.prod:
    build:
      context: .
      dockerfile: ./tools/prod/Dockerfile.test
    image: frontend:prod
    ports:
      - ${PORT}:80
    environment:
      - PORT=${PORT}
      - SERVER=${SERVER} # pass this to container to modify nginx conf
    # command: echo 'Server is running at' ${PORT}
