FROM node:latest AS builder
   
WORKDIR /app

COPY package*.json ./
RUN npm install -q
ENV PATH="/app/node_modules/.bin:${PATH}"

COPY . .
RUN npm run build


FROM nginx:mainline

COPY ./tools/prod/nginx.conf /etc/nginx
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
RUN nginx
